package com.bala.rhpam_amq_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JMSSendMessageWIH implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public JMSSendMessageWIH() {
    }




}