package com.spark;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class messagePayload implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "MESSAGEPAYLOAD_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "MESSAGEPAYLOAD_ID_SEQ", name = "MESSAGEPAYLOAD_ID_GENERATOR")
    private java.lang.Long id;

    public messagePayload() {
    }
    
    public messagePayload(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}